/**
 * Hardened HTML sanitizer for operator-authored **raw HTML** email bodies
 * (docs/ARCHITECTURE.md §4.15). Applied at the API trust boundary before a
 * pasted body is stored or sent: strips `<script>`/active content and event
 * handlers, and restricts URL schemes — while keeping the tags/attributes real
 * email needs (tables, inline styles, images, links).
 *
 * NOT applied to MJML output: that HTML is generated by our own compiler from
 * trusted-operator source and relies on `<!--[if mso]>` conditional comments the
 * sanitizer would strip. Merge values are HTML-escaped separately at render, so
 * this is defense-in-depth over pasted markup, not the primary control.
 */
import sanitizeHtmlLib from "sanitize-html";

const LAYOUT_TAGS = [
  "p", "div", "span", "br", "hr", "a", "img", "strong", "b", "em", "i", "u", "s",
  "small", "sub", "sup", "h1", "h2", "h3", "h4", "h5", "h6", "blockquote", "pre",
  "code", "ul", "ol", "li", "table", "thead", "tbody", "tfoot", "tr", "td", "th",
  "caption", "colgroup", "col", "center", "font", "section", "article", "header",
  "footer", "figure", "figcaption", "label", "address",
];

const GLOBAL_ATTRS = ["style", "class", "id", "title", "dir", "align", "valign", "width", "height", "bgcolor"];

export function sanitizeEmailHtml(html: string): string {
  return sanitizeHtmlLib(html, {
    allowedTags: LAYOUT_TAGS,
    allowedAttributes: {
      "*": GLOBAL_ATTRS,
      a: ["href", "target", "rel", "name", "data-linkid"],
      img: ["src", "alt", "border", "width", "height"],
      td: ["colspan", "rowspan", "cellpadding", "cellspacing", "border", "nowrap", ...GLOBAL_ATTRS],
      th: ["colspan", "rowspan", "cellpadding", "cellspacing", "border", "nowrap", ...GLOBAL_ATTRS],
      table: ["cellpadding", "cellspacing", "border", "role", ...GLOBAL_ATTRS],
      font: ["color", "face", "size"],
    },
    // http(s) links, mail/tel, and https/cid images. No javascript:/data:/vbscript:.
    allowedSchemes: ["http", "https", "mailto", "tel"],
    allowedSchemesByTag: { img: ["http", "https", "cid"] },
    // Drop the tag but keep its text if a tag isn't allowed (don't silently gut copy).
    disallowedTagsMode: "discard",
    allowProtocolRelative: true,
  });
}
